# Generated by Django 4.2.1 on 2023-05-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transaction_id_alter_transaction_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='sum',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='operator',
        ),
        migrations.AddField(
            model_name='transaction',
            name='number',
            field=models.IntegerField(default=21122333),
            preserve_default=False,
        ),
    ]
