# Generated by Django 4.2.1 on 2023-05-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('balance', models.CharField(max_length=13)),
                ('month', models.CharField(max_length=2)),
                ('year', models.CharField(max_length=2)),
                ('cvv', models.IntegerField()),
            ],
        ),
    ]
